apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      tier: db
  template:
    metadata:
      labels:
        app: web
        tier: db
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"

---
apiVersion: v1
kind: Service
metadata:
  name: web-mysql
  labels:
    app: web
    tier: db
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: web
    tier: db
